services:
  liquor-locker:
    # This project uses SemVer. Check the published packages for available versions.
    # Available tags as of time of writing are latest, 2, 2.1, and 2.1.0.
    image: ghcr.io/nguyenjessev/liquor-locker:2
    ports:
      # Change host port as needed to avoid collisions with other services.
      - "8080:8080"
    environment:
      # Change as needed. Must match the URL the app will be served on. (E.g. https://subdomain.mydomain.com)
      - ALLOWED_ORIGINS=https://localhost:8080
    volumes:
      # This is where the SQLite database will be stored. Change host directory to be mounted as needed.
      - ./data:/app/internal/database/data
