name: Publish Docker Images to GHCR

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Client
      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/liquor-locker-client
            ghcr.io/${{ github.repository_owner }}/liquor-locker-client:${{ github.sha }}

      # Server
      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/liquor-locker-server
            ghcr.io/${{ github.repository_owner }}/liquor-locker-server:${{ github.sha }}
